import { Column, Entity, PrimaryColumn } from 'typeorm';

/**
 * jarvis's `Lease` table, mapped read-only.
 *
 * **jarvis owns this table, not automatifier.** Its schema is managed by
 * Prisma migrations in the jarvis repository, so nothing here may ever be the
 * source of a schema change: `synchronize: false` on the entity as well as the
 * data source, and `migration:generate` must never be run against this
 * database — it would diff Prisma's schema against these partial mappings and
 * emit a migration that drops everything not listed below.
 *
 * Only the columns this service reads are mapped. Relations (`unit`,
 * `membership`, `invoice`) are left out until a feature actually needs them,
 * rather than mirroring Prisma's model wholesale and having two definitions
 * of the same table to keep in step.
 *
 * Property names match the column names exactly, because Prisma created them
 * camelCase and quoted — TypeORM's default of using the property name as the
 * column name is what makes `"startDate"` resolve without a `name:` on every
 * column.
 */
@Entity({ name: 'Lease', synchronize: false })
export class Lease {
  /** A cuid generated by Prisma, not a uuid — hence `text`, not `uuid`. */
  @PrimaryColumn('text')
  id: string;

  /**
   * Stored as UTC in `timestamp without time zone`. Read correctly only
   * because of the OID 1114 type parser in `typeorm.config.ts` — without it
   * every value here is shifted by this machine's UTC offset.
   */
  @Column('timestamp', { precision: 3 })
  startDate: Date;

  @Column('timestamp', { precision: 3 })
  endDate: Date;

  @Column('int')
  durationMonths: number;

  /** The agreed monthly rate, which may differ from the unit's asking rent. */
  @Column('int')
  monthlyRent: number;

  /** The whole term's value: `monthlyRent * durationMonths`. */
  @Column('int')
  leaseAmount: number;

  @Column('text')
  unitId: string;

  @Column('text')
  membershipId: string;

  /** Set when jarvis's auto-renewal job created this lease to succeed another. */
  @Column('text', { nullable: true })
  renewedFromId: string | null;

  @Column('timestamp', { precision: 3 })
  createdAt: Date;

  @Column('timestamp', { precision: 3 })
  updatedAt: Date;
}
